server:
  port: 8080


spring:
  ai:
    openai:
      base-url: http://127.0.0.1:8081/
      api-key: XXX
      chat:
        options:
          model: GLM-5.3
        embedding-model: text-embedding-ada-002
        embedding:
          options:
            num-batch: 1536
    agent:
      base-url: https://open.bigmodel.cn/api/coding/paas/v4/
      api-key: XXX
